# Generated by Django 5.1.6 on 2025-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('pressure', models.FloatField()),
                ('visibility', models.FloatField()),
                ('cloud_cover', models.FloatField()),
                ('prediction', models.CharField(max_length=50)),
            ],
        ),
    ]
