# Generated by Django 5.1.6 on 2025-12-11 18:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='pressure',
            field=models.FloatField(default=1015.0),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='visibility',
            field=models.FloatField(default=10.0),
        ),
    ]
